version: "3"

services:
    web:
        hostname: web
        build:
            context: .
            dockerfile: ./Dockerfile.prod
        container_name: silent-django-prod
        command: >
            bash -c "
                python manage.py migrate --no-input &&
                gunicorn base.wsgi:application -w 4 -b 0.0.0.0:8000"
        volumes:
          - .:/app
        ports:
            - "8000:8000"
        env_file:
            - .env
        restart: always

    db:
        image: postgres:latest
        container_name: silent-postgres-prod
        environment:
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        restart: always


volumes:
    postgres_data:
