version: "3"

services:
  web:
    hostname: web
    build:
      context: .
      dockerfile: ./Dockerfile.prod
    container_name: silent-django-prod
    command: >
      bash -c "
        python manage.py collectstatic --noinput &&
        python manage.py migrate --no-input &&
        gunicorn backend.wsgi:application -w 4 -b 0.0.0.0:8001
      "
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    expose:
      - "8001"
    ports:
      - "8001:8001"
    env_file:
      - .env
    restart: always

  db:
    image: postgres:latest
    container_name: silent-postgres-prod
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always


volumes:
  postgres_data:
  static_volume:
  media_volume:
  images_volume: