version: "3"

services:
    web:
        hostname: web
        build:
            context: .
            dockerfile: ./Dockerfile
        container_name: silent-django
        command: >
            bash -c "python manage.py migrate --no-input &&
                      python manage.py runserver"
        volumes:
          - .:/app
        ports:
            - "8000:8000"
        env_file:
            - .env
        restart: always

    db:
        image: postgres:latest
        container_name: silent-postgres
        environment:
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        restart: always

volumes:
    postgres_data:
