# Generated by Django 5.0.6 on 2024-10-06 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_uuid', models.CharField(max_length=250)),
                ('data_system', models.JSONField(blank=True, null=True)),
                ('data_disk', models.JSONField(blank=True, null=True)),
                ('data_disk_2', models.JSONField(blank=True, null=True)),
                ('data_system_2', models.JSONField(blank=True, null=True)),
                ('data_bios', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Computer Data',
                'verbose_name_plural': 'Computer Data',
                'ordering': ['-created_at'],
            },
        ),
    ]
