# Generated by Django 5.0.6 on 2024-10-08 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('windows_monitor', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ComputerData',
            new_name='ComputerRawData',
        ),
        migrations.AlterModelOptions(
            name='computerrawdata',
            options={'ordering': ['-created_at'], 'verbose_name': 'Computer Raw Data', 'verbose_name_plural': 'Computer Raw Data'},
        ),
    ]
