# Generated by Django 5.0.6 on 2024-10-08 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windows_monitor', '0003_computer_bios_cpu_core_disk_keyboard_memory_monitor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partition',
            name='index',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bios',
            name='major_version',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bios',
            name='minor_version',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bios',
            name='target_os',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build_number', models.CharField(max_length=250)),
                ('caption', models.CharField(max_length=250)),
                ('cs_name', models.CharField(max_length=250)),
                ('country_code', models.CharField(max_length=250)),
                ('current_timezone', models.IntegerField()),
                ('install_date', models.CharField(max_length=250)),
                ('last_boot_up', models.CharField(max_length=250)),
                ('os_architecture', models.CharField(max_length=250)),
                ('os_language', models.IntegerField()),
                ('registered_user', models.CharField(max_length=250)),
                ('serial_number', models.CharField(max_length=250)),
                ('status', models.BooleanField(default=True)),
                ('version', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='windows_monitor.computer')),
            ],
            options={
                'verbose_name': 'System',
                'verbose_name_plural': 'System',
                'ordering': ['-created_at'],
            },
        ),
    ]
