# Generated by Django 5.0.6 on 2024-10-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windows_monitor', '0004_partition_index_alter_bios_major_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkadapter',
            name='default_ip_gateway_list',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='networkadapter',
            name='dns_server_search_order_list',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='networkadapter',
            name='ip_address_list',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='networkadapter',
            name='ip_subnet_list',
            field=models.TextField(blank=True, null=True),
        ),
    ]
