# Generated by Django 5.0.6 on 2024-10-10 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windows_monitor', '0005_alter_networkadapter_default_ip_gateway_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='computerrawdata',
            name='sensor_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
