# Generated by Django 5.0.6 on 2024-10-12 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windows_monitor', '0006_computerrawdata_sensor_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPUSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('value', models.FloatField(default=0.0)),
                ('sensor_type', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='windows_monitor.computer')),
            ],
            options={
                'verbose_name': 'CPUSensor',
                'verbose_name_plural': 'CPUSensor',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GPUSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('value', models.FloatField(default=0.0)),
                ('sensor_type', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='windows_monitor.computer')),
            ],
            options={
                'verbose_name': 'GPUSensor',
                'verbose_name_plural': 'GPUSensor',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MemorySensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('value', models.FloatField(default=0.0)),
                ('sensor_type', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='windows_monitor.computer')),
            ],
            options={
                'verbose_name': 'MemorySensor',
                'verbose_name_plural': 'MemorySensor',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StorageSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('value', models.FloatField(default=0.0)),
                ('sensor_type', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='windows_monitor.computer')),
            ],
            options={
                'verbose_name': 'StorageSensor',
                'verbose_name_plural': 'StorageSensor',
                'ordering': ['-created_at'],
            },
        ),
    ]
