# Generated by Django 5.0.6 on 2024-06-14 12:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workshop", "0003_repairitem_additional_info"),
    ]

    operations = [
        migrations.AlterField(
            model_name="costs",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
