# Generated by Django 5.0.6 on 2024-06-16 20:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workshop", "0005_costs_name_alter_costs_repair_item_estimate_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="estimate",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Estimate",
                "verbose_name_plural": "Estimates",
            },
        ),
    ]
