# Generated by Django 5.0.6 on 2024-06-16 21:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workshop", "0006_alter_estimate_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="estimate",
            name="converted",
            field=models.BooleanField(default=False),
        ),
    ]
