# Generated by Django 5.0.6 on 2024-06-18 11:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workshop", "0009_notes"),
    ]

    operations = [
        migrations.CreateModel(
            name="Files",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file", models.FileField(upload_to="files/")),
            ],
            options={
                "verbose_name": "File",
                "verbose_name_plural": "Files",
                "ordering": ["-created_at"],
            },
        ),
        migrations.RemoveField(
            model_name="notes",
            name="file",
        ),
        migrations.AddField(
            model_name="notes",
            name="archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="notes",
            name="name",
            field=models.CharField(default="none", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="notes",
            name="files",
            field=models.ManyToManyField(
                blank=True, related_name="notes", to="workshop.files"
            ),
        ),
    ]
