# Generated by Django 5.0.6 on 2024-06-18 23:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workshop", "0010_files_remove_notes_file_notes_archived_notes_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notes",
            name="archived",
        ),
    ]
