# Generated by Django 5.0.6 on 2024-06-19 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workshop", "0012_repairitem_name_alter_customer_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notes",
            name="estimate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to="workshop.estimate",
            ),
        ),
    ]
